{
 "title": "MyGatling",
 "time": { "from": "2019-12-24T15:32:30.589Z", "to": "2019-12-24T15:34:40.010Z" },
 "templating": {
  "list": [
   {
    "name": "request",
    "label": "request",
    "query": "SHOW TAG VALUES WITH KEY = \"request\""
   },
   {
    "name": "writeInterval",
    "label": "gatling.data.graphite.writeInterval (sec)",
    "query": "1,5,10,30,60"
   },
   {
    "name": "g",
    "label": "granularity",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "USERS",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"active\") \nFROM \"gatling.users\"\nWHERE $timeFilter\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gatling",
     "query": "SELECT SUM(\"count\") FROM \"gatling\" WHERE (\"request\" = 'allRequests' AND \"status\" = 'all') AND $timeFilter GROUP BY time($g)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "ok" }
     ]
    }
   ]
  },
  {
   "title": "OK",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"count\") FROM \"gatling\" WHERE (\"request\" = 'allRequests' AND \"status\" = 'ok') AND $timeFilter GROUP BY time($g)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "KO",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"count\") FROM \"gatling\" WHERE (\"request\" = 'allRequests' AND \"status\" = 'ko') AND $timeFilter GROUP BY time($g)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response Time 95th",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_request",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"percentiles95\"\nFROM \"gatling\" \nWHERE (\"status\" = 'ok' ) AND $timeFilter \nGROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "THREADS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"active\") \nFROM \"gatling.users\"\n WHERE $timeFilter\n GROUP BY time($g) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Throghput",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "alias": "Req / s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"count\")  / $writeInterval FROM \"gatling\" WHERE (\"request\" = 'allRequests' AND \"status\" = 'all') AND $timeFilter GROUP BY time($g), \"simulation\", \"request\", \"status\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Users",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"active\") \nFROM \"gatling.users\"\n WHERE $timeFilter\n GROUP BY time($g) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Request Table",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(count) as Total,\nPERCENTILE(\"percentiles50\", 50)/1000 as \"75th pct\",\nPERCENTILE(\"percentiles95\", 95)/1000 as \"95th pct\",\nPERCENTILE(\"percentiles99\", 99)/1000 as \"99th pct\"\nFROM gatling \nWHERE (\"status\" = 'ok') AND $timeFilter\n GROUP BY  request",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(count) AS \"Errors,n\"\nFROM gatling  \nWHERE (\"status\" = 'ko') AND $timeFilter\n GROUP BY  request\n\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response Time Percentiles over Time (OK)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "ms", "label": "Response Time" }
   ],
   "targets": [
    {
     "alias": "$col",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$g" ], "type": "time" },
      { "params": [ "simulation" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "query": "SELECT percentile(\"percentiles50\", 50) AS \"50%\", \npercentile(\"percentiles95\", 95) AS \"95%\",\n percentile(\"percentiles99\", 99) AS \"99%\",\n percentile(\"percentiles75\", 75) AS \"75%\",\n max(\"max\") AS \"max\",\n min(\"min\") AS \"min\"\n FROM \"gatling\" \nWHERE (\"request\" = 'allRequests' AND \"status\" = 'ok') AND $timeFilter GROUP BY time($g), \"simulation\"",
     "select": [
      [
       { "params": [ "percentiles50" ], "type": "field" },
       { "params": [ "50" ], "type": "percentile" },
       { "params": [ "50%" ], "type": "alias" }
      ],
      [
       { "params": [ "percentiles95" ], "type": "field" },
       { "params": [ "95" ], "type": "percentile" },
       { "params": [ "95%" ], "type": "alias" }
      ],
      [
       { "params": [ "percentiles99" ], "type": "field" },
       { "params": [ "99" ], "type": "percentile" },
       { "params": [ "99%" ], "type": "alias" }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "max" ], "type": "alias" }
      ],
      [
       { "params": [ "percentiles75" ], "type": "field" },
       { "params": [ "75" ], "type": "percentile" },
       { "params": [ "75%" ], "type": "alias" }
      ],
      [
       { "params": [ "min" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "min" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "Threads",
     "groupBy": [
      { "params": [ "$g" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gatling.users",
     "query": "SELECT mean(\"active\") FROM \"gatling.users\" WHERE $timeFilter GROUP BY time($g) fill(null)",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}